// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/iam.proto

package iam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyKeyRequest) Reset() {
	*x = VerifyKeyRequest{}
	mi := &file_proto_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyKeyRequest) ProtoMessage() {}

func (x *VerifyKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *VerifyKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type VerifyKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ClientTier    string                 `protobuf:"bytes,2,opt,name=client_tier,json=clientTier,proto3" json:"client_tier,omitempty"` // e.g., "basic", "premium" (used for leaky bucket rate scaling)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyKeyResponse) Reset() {
	*x = VerifyKeyResponse{}
	mi := &file_proto_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyKeyResponse) ProtoMessage() {}

func (x *VerifyKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyKeyResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *VerifyKeyResponse) GetClientTier() string {
	if x != nil {
		return x.ClientTier
	}
	return ""
}

var File_proto_iam_proto protoreflect.FileDescriptor

const file_proto_iam_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/iam.proto\x12\x03iam\"H\n" +
	"\x10VerifyKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"O\n" +
	"\x11VerifyKeyResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x1f\n" +
	"\vclient_tier\x18\x02 \x01(\tR\n" +
	"clientTier2K\n" +
	"\n" +
	"IAMService\x12=\n" +
	"\fVerifyAPIKey\x12\x15.iam.VerifyKeyRequest\x1a\x16.iam.VerifyKeyResponseB\vZ\tproto/iamb\x06proto3"

var (
	file_proto_iam_proto_rawDescOnce sync.Once
	file_proto_iam_proto_rawDescData []byte
)

func file_proto_iam_proto_rawDescGZIP() []byte {
	file_proto_iam_proto_rawDescOnce.Do(func() {
		file_proto_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iam_proto_rawDesc), len(file_proto_iam_proto_rawDesc)))
	})
	return file_proto_iam_proto_rawDescData
}

var file_proto_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_iam_proto_goTypes = []any{
	(*VerifyKeyRequest)(nil),  // 0: iam.VerifyKeyRequest
	(*VerifyKeyResponse)(nil), // 1: iam.VerifyKeyResponse
}
var file_proto_iam_proto_depIdxs = []int32{
	0, // 0: iam.IAMService.VerifyAPIKey:input_type -> iam.VerifyKeyRequest
	1, // 1: iam.IAMService.VerifyAPIKey:output_type -> iam.VerifyKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_iam_proto_init() }
func file_proto_iam_proto_init() {
	if File_proto_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iam_proto_rawDesc), len(file_proto_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iam_proto_goTypes,
		DependencyIndexes: file_proto_iam_proto_depIdxs,
		MessageInfos:      file_proto_iam_proto_msgTypes,
	}.Build()
	File_proto_iam_proto = out.File
	file_proto_iam_proto_goTypes = nil
	file_proto_iam_proto_depIdxs = nil
}
